{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.prefix }}-ingress
  namespace: {{ .Values.prefix }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn:  {{ .Values.acm }}
    alb.ingress.kubernetes.io/subnets: {{ .Values.public1Id }}, {{ .Values.public2Id }}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.albSG }}
  labels:
    app: core
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "core"
              servicePort: 8080
{{- end }}
