{{- $url := .Values.repository -}}
  {{- range $i, $deploy := .Values.deployments -}}
  {{- if ne $i 0 }}
---
  {{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: torimo
  labels:
    app: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .url }}"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 50m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 256Mi
  {{- end}}
