apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
  namespace: torimo
  labels:
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: {{ quote .Values.global.post}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 50m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 256Mi
          env:
            - name: USER
              value: {{ .Values.user }}
            - name: PASSWORD
              value: {{ .Values.pass }}
            - name: DBNAME
              value: {{ .Values.db }}
            - name: URL
              value: {{ .Values.endpoint }}
